title: "Nation Settings Menu"
size: 18

items:
  1:
    material: GRAY_STAINED_GLASS_PANE
    name: " "
    slot: 0
  2:
    material: GRAY_STAINED_GLASS_PANE
    name: " "
    slot: 1
  3:
    material: GRAY_STAINED_GLASS_PANE
    name: " "
    slot: 3
  4:
    material: GRAY_STAINED_GLASS_PANE
    name: " "
    slot: 5
  5:
    material: GRAY_STAINED_GLASS_PANE
    name: " "
    slot: 7
  6:
    material: GRAY_STAINED_GLASS_PANE
    name: " "
    slot: 8
  7:
    material: NETHER_STAR
    name: "Menu Info"
    slot: 9
    lore:
      - "&7Adjust other extra"
      - "&7nation settings."
  8:
    material: GRAY_STAINED_GLASS_PANE
    name: " "
    slot: 10
  9:
    material: GRAY_STAINED_GLASS_PANE
    name: " "
    slot: 11
  10:
    material: GRAY_STAINED_GLASS_PANE
    name: " "
    slot: 12
  11:
    material: GRAY_STAINED_GLASS_PANE
    name: " "
    slot: 13
  12:
    material: GRAY_STAINED_GLASS_PANE
    name: " "
    slot: 14
  13:
    material: GRAY_STAINED_GLASS_PANE
    name: " "
    slot: 15
  14:
    material: GRAY_STAINED_GLASS_PANE
    name: " "
    slot: 16

clickable-items:
  back:
    material: OAK_DOOR
    name: "&aBack"
    slot: 17
  set-nation-spawn:
    material: GLOWSTONE
    name: "&aSet Nation Spawn"
    slot: 2
    lore:
      - ""
      - "&7Set the location for"
      - "&7teleporting with"
      - "&7/n spawn"
  set-nation-name:
    material: NAME_TAG
    name: "&aSet Nation Name"
    slot: 4
    lore:
      - ""
      - "&7Change the name"
      - "&7of your nation."
  set-nation-board:
    material: OAK_SIGN
    name: "&aSet Nation Board"
    slot: 6
    lore:
      - ""
      - "&7Set the nation board"
      - "&7of your nation."
